language: php
php:
  - 5.3
  - 5.4
before_script:
  - touch log.txt
  - chmod 777 log.txt
  - cp tests/config.inc.dist.php config.inc.php
  - mkdir tests/log.txt
  - chmod 777 tests/log.txt
  - cp tests/config.inc.dist.php tests/config.inc.php
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source --no-interaction
  - mysql -e 'create database buckutt_test;'
  - php db.php migrations:migrate --no-interaction
script: ./tests/run_all.sh


